apiVersion: v1
kind: Service
metadata:
  name: dotnet-metrics-metrics
  namespace: default
  labels:
    app: dotnet-metrics
spec:
  selector:
    serving.knative.dev/service: dotnet-metrics
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dotnet-metrics-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: dotnet-metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
